version: "3"

services:

  selenium-hub:
    image: selenium/hub:4.21.0
    platform: linux/amd64
    ports:
      - "4444:4444"   # keep only this

  chrome:
    image: selenium/node-chrome:4.21.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:4.21.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  test-runner:
    build: .
    depends_on:
      - selenium-hub
      - chrome
